### ISSUE TITLE
What is the meaning of landmarks?

### ISSUE THREAD

**Issue by zhhao1** [kamperh/eskmeans#1]
hello, i really can not understand the meaning of landmarks in eskemeans_wordseg.py. Hope you can help me, thanks a lot.

**Comment by kamperh** [comment]
Apologies since I think there should have been a better name.  "Landmarks" refer to positions where the system is allowed to place word boundaries. In this recipe, that would be where the syllable pre-segmentation system places the boundaries.  Hope that helps!

**Comment by 7zhanghao** [comment]
Thaks very much. But don't apologies, because it is my fault.  Your logic is clear, and the method is beautiful.  After reading the code in recipe_zs2017_track2-master, i have a better understand. But i still have some questions.
Fisrt, you give an example with landmarks = [1, 2, 3].  In my understanding, it means that the whole utterance have three frames and every position can be a word boundary. Is 3 represent the end of the utterance?
Second, if  landmarks = [1, 2, 3] and n_landmarks_max = 20 , the vec_ids will be [embed[0:1], embed[0:2], embed[1:2], embed[0:3], embed[1:3], embed[2:3] ].
But when downsampling,  the order of seglist to be used, which is defined in recipe_zs2017_track2master/downsample/get_seglist.py may be [embed[0:1], embed[0:2], embed[0:3], embed[1:2], embed[1:3], embed[2:3] ].  
I don’t know where I got it wrong, and I hope you can point it out. Sorry for taking your time.
![捕获](https://user-images.githubusercontent.com/46468492/88153425-f8f08000-cc37-11ea-9d4b-7a908ce42825.PNG)

**Comment by zhhao1** [comment]
> Apologies since I think there should have been a better name. "Landmarks" refer to positions where the system is allowed to place word boundaries. In this recipe, that would be where the syllable pre-segmentation system places the boundaries. Hope that helps!

Thaks very much. But don't apologies, because it is my fault. Your logic is clear, and the method is beautiful. After reading the code in recipe_zs2017_track2-master, i have a better understand. But i still have some questions.
Fisrt, you give an example with landmarks = [1, 2, 3]. In my understanding, it means that the whole utterance have three frames and every position can be a word boundary. Is 3 represent the end of the utterance?
Second, if landmarks = [1, 2, 3] and n_landmarks_max = 20 , the vec_ids will be [embed[0:1], embed[0:2], embed[1:2], embed[0:3], embed[1:3], embed[2:3] ].
But when downsampling, the order of seglist to be used, which is defined in recipe_zs2017_track2master/downsample/get_seglist.py may be [embed[0:1], embed[0:2], embed[0:3], embed[1:2], embed[1:3], embed[2:3] ].
I don’t know where I got it wrong, and I hope you can point it out. Sorry for taking your time.
![image](https://user-images.githubusercontent.com/46468492/88194382-58b74d00-cc71-11ea-9249-4c4265a17052.png)

**Comment by 7zhanghao** [comment]
![捕获](https://user-images.githubusercontent.com/46468492/88194507-80a6b080-cc71-11ea-9e1a-94a2f54aaa67.PNG)
